# Generated by Django 5.0 on 2024-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/default_profile.png', null=True, upload_to='images/avatars'),
        ),
    ]
